/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe;

/**
 *
 * @author abima
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddProduct = new javax.swing.JButton();
        ManageP = new javax.swing.JButton();
        AllP = new javax.swing.JButton();
        OrderP = new javax.swing.JButton();
        ViewOrder = new javax.swing.JButton();
        Stats = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        pmam = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddProduct.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        AddProduct.setText("Add Product");
        AddProduct.setToolTipText("");
        AddProduct.setBorder(null);
        AddProduct.setBorderPainted(false);
        AddProduct.setContentAreaFilled(false);
        AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductActionPerformed(evt);
            }
        });
        jPanel1.add(AddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 300, 70));

        ManageP.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        ManageP.setText("Manage Product");
        ManageP.setBorder(null);
        ManageP.setBorderPainted(false);
        ManageP.setContentAreaFilled(false);
        ManageP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePActionPerformed(evt);
            }
        });
        jPanel1.add(ManageP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 300, 70));

        AllP.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        AllP.setText("All Products");
        AllP.setBorder(null);
        AllP.setBorderPainted(false);
        AllP.setContentAreaFilled(false);
        jPanel1.add(AllP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 493, 310, 70));

        OrderP.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        OrderP.setText("Order");
        OrderP.setBorder(null);
        OrderP.setBorderPainted(false);
        OrderP.setContentAreaFilled(false);
        jPanel1.add(OrderP, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 290, 90));

        ViewOrder.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        ViewOrder.setText("View Orders");
        ViewOrder.setBorder(null);
        ViewOrder.setBorderPainted(false);
        ViewOrder.setContentAreaFilled(false);
        jPanel1.add(ViewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 290, 90));

        Stats.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        Stats.setText("Statistics");
        Stats.setBorder(null);
        Stats.setBorderPainted(false);
        Stats.setContentAreaFilled(false);
        Stats.setMargin(new java.awt.Insets(3, 14, 3, 14));
        Stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatsActionPerformed(evt);
            }
        });
        jPanel1.add(Stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 290, 90));

        date.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Senin, 10 Juni 2024");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 170, 30));

        jam.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jam.setForeground(new java.awt.Color(255, 255, 255));
        jam.setText("00 : 00");
        jPanel1.add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 70, 40));

        pmam.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        pmam.setForeground(new java.awt.Color(255, 255, 255));
        pmam.setText("PM");
        jPanel1.add(pmam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 60, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MainMenu.png"))); // NOI18N
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatsActionPerformed

    private void AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProductActionPerformed

    private void ManagePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManagePActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProduct;
    private javax.swing.JButton AllP;
    private javax.swing.JButton ManageP;
    private javax.swing.JButton OrderP;
    private javax.swing.JButton Stats;
    private javax.swing.JButton ViewOrder;
    private javax.swing.JLabel back;
    private javax.swing.JLabel date;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel pmam;
    // End of variables declaration//GEN-END:variables
}
